<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OJU0P6V" failures="1" tests="31" name="com.qa.tests.PostAPItest" time="106.888" errors="1" timestamp="2022-12-13T14:12:08 IST" skipped="3">
  <testcase classname="com.qa.tests.PostAPItest" name="Assume_get_access_token" time="4.329"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Assume_Individuo_Certificate" time="10.450"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Assume_Patroons_Certificate" time="6.668"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CFSE_Test_get_access_token" time="1.818"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CFSE_get_informacionDeDeauda" time="17.129"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CFSE_get_certificacionDeDeauda" time="1.711"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CFSE_get_certificacionDeVegencia" time="1.351"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CFSE_get_fondoPing" time="1.354"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Estado_Compliance" time="1.382"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Estado_Ping" time="0.985"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Estado_Certificado" time="12.038"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_corporate_ping" time="2.088"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_corporate_compliance" time="2.154"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_corporate_authorize" time="4.040"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_Corporate_complianceDocuments" time="1.605"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_individual_ping" time="1.676"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_authorize_individual" time="2.546"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_complianceDocuments_ind" time="10.586">
    <failure message="status code is not 200 expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: status code is not 200 expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at com.qa.tests.PostAPItest.Hacienda_complianceDocuments_ind(PostAPItest.java:983)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Hacienda_complianceDocuments_ind -->
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="PostAPITest_cap_request" time="2.722"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="PostAPITest_Retrieve" time="2.985"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="PostAPITest_Justicia_Validate" time="3.049"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="PostAPITest_Justicia_CriminalRecord_CheckInquiry" time="0.008">
    <error message="Illegal character in path at index 48: https://suri.cjis.pr.gov/identity/criminal/check	" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Illegal character in path at index 48: https://suri.cjis.pr.gov/identity/criminal/check
at java.base/java.net.URI.create(URI.java:906)
at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
at com.qa.client.RestClient.get(RestClient.java:43)
at com.qa.tests.PostAPItest.PostAPITest_Justicia_CriminalRecord_CheckInquiry(PostAPItest.java:1169)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.URISyntaxException: Illegal character in path at index 48: https://suri.cjis.pr.gov/identity/criminal/check
at java.base/java.net.URI$Parser.fail(URI.java:2974)
at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3227)
at java.base/java.net.URI$Parser.parse(URI.java:3175)
at java.base/java.net.URI.<init>(URI.java:623)
at java.base/java.net.URI.create(URI.java:904)
... 31 more
]]>
    </error>
  </testcase> <!-- PostAPITest_Justicia_CriminalRecord_CheckInquiry -->
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Crim360_Authenticate" time="1.742"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CRIM360_Certification" time="2.882"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CRIM360_Crimcompliance" time="1.382"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="CRIM360_FileContent" time="3.396"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="DTOP_token" time="1.758"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="get_DTOPGetPhoto" time="3.054"/>
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="PostAPITest_Validate">
    <skipped/>
  </testcase> <!-- PostAPITest_Validate -->
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="Hacienda_compliance_individual">
    <skipped/>
  </testcase> <!-- Hacienda_compliance_individual -->
  <system-out/>
  <testcase classname="com.qa.tests.PostAPItest" name="get_GetLicense">
    <skipped/>
  </testcase> <!-- get_GetLicense -->
  <system-out/>
</testsuite> <!-- com.qa.tests.PostAPItest -->
